// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXnYhD3jS99luj_KT5JoQFnsHM0GsMqqw',
    appId: '1:597861685440:web:9c2b921826cb176288f525',
    messagingSenderId: '597861685440',
    projectId: 'nuance-ec8ce',
    authDomain: 'nuance-ec8ce.firebaseapp.com',
    storageBucket: 'nuance-ec8ce.appspot.com',
    measurementId: 'G-EBYPJ8G7MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtszMqgbVTbTwqYKFDRZid1SsU4ap8ktg',
    appId: '1:111351014313:android:6158799cc0877bad26dab8',
    messagingSenderId: '111351014313',
    projectId: 'nuancedemo-789d4',
    storageBucket: 'nuancedemo-789d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGplR3u8Y2fC87rEySfM5xPKlLsVlLWl4',
    appId: '1:111351014313:ios:55ee759e42f51e8f26dab8',
    messagingSenderId: '111351014313',
    projectId: 'nuancedemo-789d4',
    storageBucket: 'nuancedemo-789d4.appspot.com',
    iosBundleId: 'com.example.nuance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz9K5lgzDGHqMn09Snfpr_HybY3FvZzJs',
    appId: '1:597861685440:ios:e86c14d39629435488f525',
    messagingSenderId: '597861685440',
    projectId: 'nuance-ec8ce',
    storageBucket: 'nuance-ec8ce.appspot.com',
    iosBundleId: 'com.discovernuance.nuance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXnYhD3jS99luj_KT5JoQFnsHM0GsMqqw',
    appId: '1:597861685440:web:0c332696c0ab44bc88f525',
    messagingSenderId: '597861685440',
    projectId: 'nuance-ec8ce',
    authDomain: 'nuance-ec8ce.firebaseapp.com',
    storageBucket: 'nuance-ec8ce.appspot.com',
    measurementId: 'G-H09BL7FB6L',
  );
}